In [101]:
import pandas as pd

In [102]:
train = pd.read_csv('data/train.csv')

## Univariate analyzis

In [103]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660611 entries, 0 to 660610
Data columns (total 16 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   observation_id                            660611 non-null  object
 1   Type                                      660611 non-null  object
 2   Date                                      660611 non-null  object
 3   Part of a policing operation              507047 non-null  object
 4   Latitude                                  548295 non-null  float64
 5   Longitude                                 548295 non-null  float64
 6   Gender                                    660611 non-null  object
 7   Age range                                 660611 non-null  object
 8   Self-defined ethnicity                    655037 non-null  object
 9   Officer-defined ethnicity                 660611 non-null  object
 10  Legislation                               632671 non-null  object
 11  Object of search                          660611 non-null  object
 12  Outcome                                   660611 non-null  object
 13  Outcome linked to object of search        187511 non-null  object
 14  Removal of more than just outer clothing  234062 non-null  object
 15  station                                   660611 non-null  object
dtypes: float64(2), object(14)
memory usage: 80.6+ MB

In [4]:
train.head()

,observation_id,Type,Date,Part of a policing operation,Latitude,Longitude,Gender,Age range,Self-defined ethnicity,Officer-defined ethnicity,Legislation,Object of search,Outcome,Outcome linked to object of search,Removal of more than just outer clothing,station
0,34d76816-cfc2-4bdd-b3a2-bf0c40b12689,Person search,2019-12-01T00:00:00+00:00,True,NaN,NaN,Male,18-24,Asian/Asian British - Any other Asian background,Asian,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,NaN,False,devon-and-cornwall
1,83c87ec1-e6d4-4bbb-8e0c-159516706359,Person search,2019-12-01T00:09:00+00:00,True,NaN,NaN,Male,18-24,NaN,White,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,NaN,False,devon-and-cornwall
2,8c2eae4b-035a-492f-92d6-cd27e6c900a1,Person search,2019-12-01T00:10:00+00:00,True,NaN,NaN,Female,18-24,White - English/Welsh/Scottish/Northern Irish/...,White,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,NaN,False,devon-and-cornwall
3,e63a036a-a728-4efe-8e08-7198f56d6d0a,Person search,2019-12-01T00:10:00+00:00,False,NaN,NaN,Male,18-24,NaN,Asian,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,NaN,False,devon-and-cornwall
4,40c70aca-1f7f-4efe-8c5b-ade0f2e9937d,Person search,2019-12-01T00:12:00+00:00,True,50.368247,-4.126646,Male,18-24,NaN,White,Misuse of Drugs Act 1971 (section 23),Controlled drugs,A no further action disposal,NaN,False,devon-and-cornwall

In [104]:
print(train['Type'].value_counts(dropna=False))
train['Type'].value_counts(dropna=False,normalize=True)

Person search                503503
Person and Vehicle search    156156
Vehicle search                  952
Name: Type, dtype: int64

Person search                0.762178
Person and Vehicle search    0.236381
Vehicle search               0.001441
Name: Type, dtype: float64

In [105]:
print(train['Part of a policing operation'].value_counts(dropna=False))
train['Part of a policing operation'].value_counts(dropna=False,normalize=True)

False    490773
NaN      153564
True      16274
Name: Part of a policing operation, dtype: int64

False    0.742908
NaN      0.232458
True     0.024635
Name: Part of a policing operation, dtype: float64

In [106]:
print(train['Gender'].value_counts(dropna=False))
train['Gender'].value_counts(dropna=False,normalize=True)

Male      605422
Female     54812
Other        377
Name: Gender, dtype: int64

Male      0.916458
Female    0.082972
Other     0.000571
Name: Gender, dtype: float64

In [107]:
print(train['Age range'].value_counts(dropna=False))
train['Age range'].value_counts(dropna=False,normalize=True)

18-24       241905
25-34       158181
10-17       131763
over 34     128378
under 10       384
Name: Age range, dtype: int64

18-24       0.366184
25-34       0.239447
10-17       0.199456
over 34     0.194332
under 10    0.000581
Name: Age range, dtype: float64

In [10]:
print(train['Self-defined ethnicity'].value_counts(dropna=False))
train['Self-defined ethnicity'].value_counts(dropna=False,normalize=True)

White - English/Welsh/Scottish/Northern Irish/British                                   272053
Other ethnic group - Not stated                                                          86421
White - Any other White background                                                       57875
Black/African/Caribbean/Black British - Any other Black/African/Caribbean background     54036
Black/African/Caribbean/Black British - African                                          43297
Black/African/Caribbean/Black British - Caribbean                                        31315
Asian/Asian British - Any other Asian background                                         29169
Asian/Asian British - Bangladeshi                                                        17083
Asian/Asian British - Pakistani                                                          15720
Other ethnic group - Any other ethnic group                                              11276
Mixed/Multiple ethnic groups - Any other Mixed/Multiple ethnic background                 9601
Asian/Asian British - Indian                                                              8191
Mixed/Multiple ethnic groups - White and Black Caribbean                                  7701
NaN                                                                                       5574
White - Irish                                                                             5059
Mixed/Multiple ethnic groups - White and Black African                                    2442
Mixed/Multiple ethnic groups - White and Asian                                            2025
Asian/Asian British - Chinese                                                              929
White - Gypsy or Irish Traveller                                                           755
Other ethnic group - Arab                                                                   89
Name: Self-defined ethnicity, dtype: int64

White - English/Welsh/Scottish/Northern Irish/British                                   0.411820
Other ethnic group - Not stated                                                         0.130820
White - Any other White background                                                      0.087608
Black/African/Caribbean/Black British - Any other Black/African/Caribbean background    0.081797
Black/African/Caribbean/Black British - African                                         0.065541
Black/African/Caribbean/Black British - Caribbean                                       0.047403
Asian/Asian British - Any other Asian background                                        0.044155
Asian/Asian British - Bangladeshi                                                       0.025859
Asian/Asian British - Pakistani                                                         0.023796
Other ethnic group - Any other ethnic group                                             0.017069
Mixed/Multiple ethnic groups - Any other Mixed/Multiple ethnic background               0.014534
Asian/Asian British - Indian                                                            0.012399
Mixed/Multiple ethnic groups - White and Black Caribbean                                0.011657
NaN                                                                                     0.008438
White - Irish                                                                           0.007658
Mixed/Multiple ethnic groups - White and Black African                                  0.003697
Mixed/Multiple ethnic groups - White and Asian                                          0.003065
Asian/Asian British - Chinese                                                           0.001406
White - Gypsy or Irish Traveller                                                        0.001143
Other ethnic group - Arab                                                               0.000135
Name: Self-defined ethnicity, dtype: float64

In [11]:
print(train['Officer-defined ethnicity'].value_counts(dropna=False))
train['Officer-defined ethnicity'].value_counts(dropna=False,normalize=True)

White    378311
Black    174593
Asian     86035
Other     19842
Mixed      1830
Name: Officer-defined ethnicity, dtype: int64

White    0.572668
Black    0.264290
Asian    0.130235
Other    0.030036
Mixed    0.002770
Name: Officer-defined ethnicity, dtype: float64

In [12]:
print(train['Legislation'].value_counts(dropna=False))
train['Legislation'].value_counts(dropna=False,normalize=True)

Misuse of Drugs Act 1971 (section 23)                      385307
Police and Criminal Evidence Act 1984 (section 1)          224682
NaN                                                         27940
Criminal Justice and Public Order Act 1994 (section 60)     17259
Firearms Act 1968 (section 47)                               4352
Criminal Justice Act 1988 (section 139B)                      746
Poaching Prevention Act 1862 (section 2)                      152
Psychoactive Substances Act 2016 (s36(2))                      90
Wildlife and Countryside Act 1981 (section 19)                 31
Police and Criminal Evidence Act 1984 (section 6)              15
Aviation Security Act 1982 (section 27(1))                     11
Customs and Excise Management Act 1979 (section 163)           10
Crossbows Act 1987 (section 4)                                  5
Psychoactive Substances Act 2016 (s37(2))                       4
Protection of Badgers Act 1992 (section 11)                     4
Public Stores Act 1875 (section 6)                              1
Deer Act 1991 (section 12)                                      1
Conservation of Seals Act 1970 (section 4)                      1
Name: Legislation, dtype: int64

Misuse of Drugs Act 1971 (section 23)                      0.583259
Police and Criminal Evidence Act 1984 (section 1)          0.340112
NaN                                                        0.042294
Criminal Justice and Public Order Act 1994 (section 60)    0.026126
Firearms Act 1968 (section 47)                             0.006588
Criminal Justice Act 1988 (section 139B)                   0.001129
Poaching Prevention Act 1862 (section 2)                   0.000230
Psychoactive Substances Act 2016 (s36(2))                  0.000136
Wildlife and Countryside Act 1981 (section 19)             0.000047
Police and Criminal Evidence Act 1984 (section 6)          0.000023
Aviation Security Act 1982 (section 27(1))                 0.000017
Customs and Excise Management Act 1979 (section 163)       0.000015
Crossbows Act 1987 (section 4)                             0.000008
Psychoactive Substances Act 2016 (s37(2))                  0.000006
Protection of Badgers Act 1992 (section 11)                0.000006
Public Stores Act 1875 (section 6)                         0.000002
Deer Act 1991 (section 12)                                 0.000002
Conservation of Seals Act 1970 (section 4)                 0.000002
Name: Legislation, dtype: float64

In [13]:
print(train['Object of search'].value_counts(dropna=False))
train['Object of search'].value_counts(dropna=False,normalize=True)

Controlled drugs                              398873
Offensive weapons                             102107
Stolen goods                                   67636
Article for use in theft                       30836
Evidence of offences under the Act             19911
Anything to threaten or harm anyone            19762
Articles for use in criminal damage            11060
Firearms                                        5479
Fireworks                                       2948
Psychoactive substances                         1701
Detailed object of search unavailable            129
Game or poaching equipment                       102
Evidence of wildlife offences                     25
Goods on which duty has not been paid etc.        23
Crossbows                                         17
Seals or hunting equipment                         2
Name: Object of search, dtype: int64

Controlled drugs                              0.603794
Offensive weapons                             0.154564
Stolen goods                                  0.102384
Article for use in theft                      0.046678
Evidence of offences under the Act            0.030140
Anything to threaten or harm anyone           0.029915
Articles for use in criminal damage           0.016742
Firearms                                      0.008294
Fireworks                                     0.004463
Psychoactive substances                       0.002575
Detailed object of search unavailable         0.000195
Game or poaching equipment                    0.000154
Evidence of wildlife offences                 0.000038
Goods on which duty has not been paid etc.    0.000035
Crossbows                                     0.000026
Seals or hunting equipment                    0.000003
Name: Object of search, dtype: float64

In [16]:
print(train['Outcome'].value_counts(dropna=False))
train['Outcome'].value_counts(dropna=False,normalize=True)

A no further action disposal                                    455342
Arrest                                                           94118
Community resolution                                             41311
Khat or Cannabis warning                                         17173
Nothing found - no further action                                16188
Summons / charged by post                                        12232
Penalty Notice for Disorder                                      11214
Suspect arrested                                                  4649
Caution (simple or conditional)                                   3179
Offender given drugs possession warning                           2102
Local resolution                                                  1333
Suspect summonsed to court                                         636
Article found - Detailed outcome unavailable                       524
Offender given penalty notice                                      414
Offender cautioned                                                 189
Suspected psychoactive substances seized - No further action         7
Name: Outcome, dtype: int64

A no further action disposal                                    0.689274
Arrest                                                          0.142471
Community resolution                                            0.062535
Khat or Cannabis warning                                        0.025996
Nothing found - no further action                               0.024505
Summons / charged by post                                       0.018516
Penalty Notice for Disorder                                     0.016975
Suspect arrested                                                0.007037
Caution (simple or conditional)                                 0.004812
Offender given drugs possession warning                         0.003182
Local resolution                                                0.002018
Suspect summonsed to court                                      0.000963
Article found - Detailed outcome unavailable                    0.000793
Offender given penalty notice                                   0.000627
Offender cautioned                                              0.000286
Suspected psychoactive substances seized - No further action    0.000011
Name: Outcome, dtype: float64

In [15]:
print(train['Outcome linked to object of search'].value_counts(dropna=False))
train['Outcome linked to object of search'].value_counts(dropna=False,normalize=True)

NaN      473100
True     100273
False     87238
Name: Outcome linked to object of search, dtype: int64

NaN      0.716155
True     0.151788
False    0.132057
Name: Outcome linked to object of search, dtype: float64

In [17]:
print(train['Removal of more than just outer clothing'].value_counts(dropna=False))
train['Removal of more than just outer clothing'].value_counts(dropna=False, normalize=True)

NaN      426549
False    223397
True      10665
Name: Removal of more than just outer clothing, dtype: int64

NaN      0.645689
False    0.338167
True     0.016144
Name: Removal of more than just outer clothing, dtype: float64

In [20]:
print(train['station'].nunique())
print(train['station'].value_counts(dropna=False))
train['station'].value_counts(dropna=False, normalize=True)

42
metropolitan          351294
merseyside             41597
essex                  19039
thames-valley          17898
west-yorkshire         17144
hampshire              13963
hertfordshire          13328
kent                   13309
south-yorkshire        13165
surrey                 10972
avon-and-somerset      10015
btp                     9555
lancashire              9154
west-mercia             7904
devon-and-cornwall      7569
staffordshire           7318
nottinghamshire         7103
northumbria             7049
sussex                  6941
north-wales             5215
lincolnshire            5047
leicestershire          4980
greater-manchester      4851
cheshire                4845
norfolk                 4779
dyfed-powys             4315
bedfordshire            4209
humberside              3783
city-of-london          3575
northamptonshire        3526
suffolk                 3355
warwickshire            3249
gloucestershire         2871
derbyshire              2852
dorset                  2825
durham                  2778
north-yorkshire         2234
cumbria                 2129
cleveland               1872
wiltshire               1355
cambridgeshire           877
gwent                    772
Name: station, dtype: int64

metropolitan          0.531771
merseyside            0.062967
essex                 0.028820
thames-valley         0.027093
west-yorkshire        0.025952
hampshire             0.021136
hertfordshire         0.020175
kent                  0.020147
south-yorkshire       0.019929
surrey                0.016609
avon-and-somerset     0.015160
btp                   0.014464
lancashire            0.013857
west-mercia           0.011965
devon-and-cornwall    0.011458
staffordshire         0.011078
nottinghamshire       0.010752
northumbria           0.010670
sussex                0.010507
north-wales           0.007894
lincolnshire          0.007640
leicestershire        0.007538
greater-manchester    0.007343
cheshire              0.007334
norfolk               0.007234
dyfed-powys           0.006532
bedfordshire          0.006371
humberside            0.005727
city-of-london        0.005412
northamptonshire      0.005337
suffolk               0.005079
warwickshire          0.004918
gloucestershire       0.004346
derbyshire            0.004317
dorset                0.004276
durham                0.004205
north-yorkshire       0.003382
cumbria               0.003223
cleveland             0.002834
wiltshire             0.002051
cambridgeshire        0.001328
gwent                 0.001169
Name: station, dtype: float64

In [21]:
print(train['Date'].value_counts(dropna=False))

2018-08-04T23:00:00+00:00    71
2019-01-25T00:00:00+00:00    63
2019-01-12T00:00:00+00:00    62
2018-08-27T14:00:00+00:00    60
2019-01-26T00:00:00+00:00    57
                             ..
2019-05-15T02:23:05+00:00     1
2019-03-26T14:35:47+00:00     1
2019-01-22T13:00:18+00:00     1
2018-02-22T18:02:00+00:00     1
2019-10-26T13:53:52+00:00     1
Name: Date, Length: 339759, dtype: int64

In [24]:
print(train['Latitude'].value_counts(dropna=False))
print(train['Latitude'].value_counts(dropna=False,normalize=True))

NaN          112316
51.378427      1286
51.402747      1243
51.539189      1104
51.522956       830
              ...
50.819422         1
52.016083         1
52.266771         1
53.232820         1
51.517360         1
Name: Latitude, Length: 103639, dtype: int64
NaN          0.170018
51.378427    0.001947
51.402747    0.001882
51.539189    0.001671
51.522956    0.001256
               ...
50.819422    0.000002
52.016083    0.000002
52.266771    0.000002
53.232820    0.000002
51.517360    0.000002
Name: Latitude, Length: 103639, dtype: float64

In [25]:
print(train['Longitude'].value_counts(dropna=False))
print(train['Longitude'].value_counts(dropna=False,normalize=True))

 NaN         112316
-0.102657      1286
-0.509813      1243
-0.142008      1104
-0.193713       830
              ...
-4.709263         1
-1.919514         1
 1.325050         1
-1.516549         1
-1.749171         1
Name: Longitude, Length: 105046, dtype: int64
 NaN         0.170018
-0.102657    0.001947
-0.509813    0.001882
-0.142008    0.001671
-0.193713    0.001256
               ...
-4.709263    0.000002
-1.919514    0.000002
 1.325050    0.000002
-1.516549    0.000002
-1.749171    0.000002
Name: Longitude, Length: 105046, dtype: float64

## Target

In [27]:
train['Outcome linked to object of search'].value_counts(dropna=False)
train['Outcome'].value_counts(dropna=False)

NaN      473100
True     100273
False     87238
Name: Outcome linked to object of search, dtype: int64

In [46]:
# pd.crosstab(index=train["Outcome"], columns=train["Outcome linked to object of search"],
#             margins=True, margins_name="Total",dropna=False)

pd.crosstab(train["Outcome"],train["Outcome linked to object of search"],
            margins=True, margins_name="Total",dropna=False)

Outcome linked to object of search                  False    True   Total
Outcome
A no further action disposal                        60744   36521  455342
Arrest                                              12827   27864   94118
Article found - Detailed outcome unavailable          164     254     524
Caution (simple or conditional)                       365    2367    3179
Community resolution                                 3508    7802   41311
Khat or Cannabis warning                             1606   12823   17173
Local resolution                                      650     436    1333
Nothing found - no further action                    3291    1466   16188
Offender cautioned                                     25     137     189
Offender given drugs possession warning               198     990    2102
Offender given penalty notice                          84     115     414
Penalty Notice for Disorder                          1158    1954   11214
Summons / charged by post                            1566    5652   12232
Suspect arrested                                      936    1580    4649
Suspect summonsed to court                            114     308     636
Suspected psychoactive substances seized - No f...      2       4       7
Total                                               87238  100273  660611

In [49]:
pd.crosstab(train["Object of search"],train["Outcome"])

Outcome,A no further action disposal,Arrest,Article found - Detailed outcome unavailable,Caution (simple or conditional),Community resolution,Khat or Cannabis warning,Local resolution,Nothing found - no further action,Offender cautioned,Offender given drugs possession warning,Offender given penalty notice,Penalty Notice for Disorder,Summons / charged by post,Suspect arrested,Suspect summonsed to court,Suspected psychoactive substances seized - No further action
Object of search,,,,,,,,,,,,,,,,
Anything to threaten or harm anyone,16710,1503,31,24,892,71,5,205,0,4,1,167,96,53,0,0
Article for use in theft,22815,4505,40,66,697,306,97,1326,6,28,16,177,445,288,24,0
Articles for use in criminal damage,5982,1101,0,20,369,56,68,2304,0,61,31,161,78,798,31,0
Controlled drugs,262985,50346,355,2795,32823,15837,868,9423,163,1949,320,8726,9233,2582,463,5
Crossbows,10,5,0,0,1,1,0,0,0,0,0,0,0,0,0,0
Detailed object of search unavailable,46,13,7,1,1,2,5,43,0,0,0,0,0,8,3,0
Evidence of offences under the Act,15356,3611,1,10,492,53,10,63,0,0,0,171,128,15,1,0
Evidence of wildlife offences,19,1,0,0,2,0,0,0,0,0,0,0,3,0,0,0
Firearms,3915,1061,2,11,123,27,8,205,0,3,0,30,38,54,2,0
Fireworks,2586,214,0,4,90,7,0,5,0,0,0,20,21,1,0,0
Game or poaching equipment,67,2,0,1,8,1,0,4,0,0,0,1,15,1,2,0
Goods on which duty has not been paid etc.,12,5,1,0,1,0,0,3,0,0,0,0,1,0,0,0
Offensive weapons,79410,16638,49,95,2069,439,97,1379,6,29,15,768,704,380,28,1
Psychoactive substances,981,263,1,8,248,149,0,0,0,0,0,11,39,1,0,0
Seals or hunting equipment,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Stolen goods,44447,14849,37,144,3495,224,175,1228,14,28,31,982,1431,468,82,1

In [50]:
target1 = ['Arrest','Article found - Detailed outcome unavailable','Caution (simple or conditional)','Community resolution',
'Khat or Cannabis warning','Offender cautioned','Offender given drugs possession warning','Offender given penalty notice',
'Penalty Notice for Disorder','Summons / charged by post','Suspect arrested','Suspect summonsed to court']

target2 = ['Arrest','Article found - Detailed outcome unavailable','Summons / charged by post','Suspect arrested',
'Suspect summonsed to court']

In [53]:
train['target1'] = train['Outcome'].isin(target1)
train['target2'] = train['Outcome'].isin(target2)

In [55]:
print(train['target1'].value_counts(dropna=False))
print(train['target1'].value_counts(dropna=False,normalize=True))

False    472870
True     187741
Name: target1, dtype: int64
False    0.715807
True     0.284193
Name: target1, dtype: float64

In [56]:
print(train['target2'].value_counts(dropna=False))
print(train['target2'].value_counts(dropna=False,normalize=True))

False    548452
True     112159
Name: target2, dtype: int64
False    0.830219
True     0.169781
Name: target2, dtype: float64

In [65]:
pd.crosstab(train["Object of search"],train["target1"],normalize='index')

target1                                        False     True
Object of search
Anything to threaten or harm anyone         0.856189  0.143811
Article for use in theft                    0.786029  0.213971
Articles for use in criminal damage         0.755335  0.244665
Controlled drugs                            0.685133  0.314867
Crossbows                                   0.588235  0.411765
Detailed object of search unavailable       0.728682  0.271318
Evidence of offences under the Act          0.774898  0.225102
Evidence of wildlife offences               0.760000  0.240000
Firearms                                    0.753422  0.246578
Fireworks                                   0.878901  0.121099
Game or poaching equipment                  0.696078  0.303922
Goods on which duty has not been paid etc.  0.652174  0.347826
Offensive weapons                           0.792179  0.207821
Psychoactive substances                     0.576720  0.423280
Seals or hunting equipment                  0.500000  0.500000
Stolen goods                                0.677908  0.322092

In [66]:
pd.crosstab(train["Object of search"],train["target2"],normalize='index')

target2                                        False     True
Object of search
Anything to threaten or harm anyone         0.914837  0.085163
Article for use in theft                    0.828058  0.171942
Articles for use in criminal damage         0.818445  0.181555
Controlled drugs                            0.842108  0.157892
Crossbows                                   0.705882  0.294118
Detailed object of search unavailable       0.759690  0.240310
Evidence of offences under the Act          0.811361  0.188639
Evidence of wildlife offences               0.840000  0.160000
Firearms                                    0.788830  0.211170
Fireworks                                   0.919946  0.080054
Game or poaching equipment                  0.803922  0.196078
Goods on which duty has not been paid etc.  0.695652  0.304348
Offensive weapons                           0.825683  0.174317
Psychoactive substances                     0.821282  0.178718
Seals or hunting equipment                  0.500000  0.500000
Stolen goods                                0.750621  0.249379

In [69]:
pd.crosstab(train["station"],train["target1"],normalize='index')

target1                False     True
station
avon-and-somerset   0.699151  0.300849
bedfordshire        0.749109  0.250891
btp                 0.729566  0.270434
cambridgeshire      0.629418  0.370582
cheshire            0.615067  0.384933
city-of-london      0.664336  0.335664
cleveland           0.679487  0.320513
cumbria             0.726163  0.273837
derbyshire          0.686185  0.313815
devon-and-cornwall  0.693090  0.306910
dorset              0.760708  0.239292
durham              0.543557  0.456443
dyfed-powys         0.686211  0.313789
essex               0.694154  0.305846
gloucestershire     0.716823  0.283177
greater-manchester  0.737580  0.262420
gwent               0.961140  0.038860
hampshire           0.569147  0.430853
hertfordshire       0.695303  0.304697
humberside          0.750991  0.249009
kent                0.588249  0.411751
lancashire          0.796264  0.203736
leicestershire      0.679719  0.320281
lincolnshire        0.781058  0.218942
merseyside          0.775993  0.224007
metropolitan        0.726366  0.273634
norfolk             0.765014  0.234986
north-wales         0.808821  0.191179
north-yorkshire     0.795882  0.204118
northamptonshire    0.715258  0.284742
northumbria         0.706058  0.293942
nottinghamshire     0.650993  0.349007
south-yorkshire     0.746449  0.253551
staffordshire       0.682837  0.317163
suffolk             0.703130  0.296870
surrey              0.713544  0.286456
sussex              0.581184  0.418816
thames-valley       0.749357  0.250643
warwickshire        0.692521  0.307479
west-mercia         0.654605  0.345395
west-yorkshire      0.638999  0.361001
wiltshire           0.769742  0.230258

In [70]:
pd.crosstab(train["station"],train["target2"],normalize='index')

target2                False     True
station
avon-and-somerset   0.808787  0.191213
bedfordshire        0.879781  0.120219
btp                 0.817687  0.182313
cambridgeshire      0.735462  0.264538
cheshire            0.781837  0.218163
city-of-london      0.747692  0.252308
cleveland           0.728098  0.271902
cumbria             0.802255  0.197745
derbyshire          0.802945  0.197055
devon-and-cornwall  0.837363  0.162637
dorset              0.849558  0.150442
durham              0.735781  0.264219
dyfed-powys         0.796524  0.203476
essex               0.862755  0.137245
gloucestershire     0.822013  0.177987
greater-manchester  0.839002  0.160998
gwent               0.987047  0.012953
hampshire           0.738881  0.261119
hertfordshire       0.806498  0.193502
humberside          0.832672  0.167328
kent                0.784356  0.215644
lancashire          0.855473  0.144527
leicestershire      0.808032  0.191968
lincolnshire        0.854171  0.145829
merseyside          0.870784  0.129216
metropolitan        0.840271  0.159729
norfolk             0.861059  0.138941
north-wales         0.864046  0.135954
north-yorkshire     0.833930  0.166070
northamptonshire    0.818491  0.181509
northumbria         0.752589  0.247411
nottinghamshire     0.760805  0.239195
south-yorkshire     0.832359  0.167641
staffordshire       0.820853  0.179147
suffolk             0.811326  0.188674
surrey              0.849344  0.150656
sussex              0.821928  0.178072
thames-valley       0.826908  0.173092
warwickshire        0.786088  0.213912
west-mercia         0.755440  0.244560
west-yorkshire      0.759099  0.240901
wiltshire           0.869373  0.130627

## Discrimination analyzis

In [74]:
print(train['Gender'].value_counts(dropna=False,normalize=True))
pd.crosstab(train["station"],train["Gender"],normalize='index')

Male      0.916458
Female    0.082972
Other     0.000571
Name: Gender, dtype: float64

Gender                Female      Male     Other
station
avon-and-somerset   0.133400  0.866600  0.000000
bedfordshire        0.090045  0.908767  0.001188
btp                 0.073574  0.926112  0.000314
cambridgeshire      0.156214  0.842645  0.001140
cheshire            0.088545  0.911455  0.000000
city-of-london      0.099021  0.900140  0.000839
cleveland           0.093483  0.906517  0.000000
cumbria             0.142320  0.857210  0.000470
derbyshire          0.097826  0.901823  0.000351
devon-and-cornwall  0.155635  0.844365  0.000000
dorset              0.152566  0.847434  0.000000
durham              0.095392  0.902088  0.002520
dyfed-powys         0.150174  0.849826  0.000000
essex               0.112821  0.887179  0.000000
gloucestershire     0.112156  0.887844  0.000000
greater-manchester  0.077922  0.922078  0.000000
gwent               0.075130  0.924870  0.000000
hampshire           0.122395  0.874311  0.003294
hertfordshire       0.108043  0.891957  0.000000
humberside          0.113402  0.886598  0.000000
kent                0.118341  0.881659  0.000000
lancashire          0.084881  0.913043  0.002076
leicestershire      0.089759  0.910241  0.000000
lincolnshire        0.115910  0.883495  0.000594
merseyside          0.059812  0.939996  0.000192
metropolitan        0.066693  0.933008  0.000299
norfolk             0.146683  0.841808  0.011509
north-wales         0.114669  0.885331  0.000000
north-yorkshire     0.169651  0.830349  0.000000
northamptonshire    0.087635  0.912365  0.000000
northumbria         0.101858  0.896581  0.001561
nottinghamshire     0.068985  0.930452  0.000563
south-yorkshire     0.110444  0.889556  0.000000
staffordshire       0.104673  0.893687  0.001640
suffolk             0.127571  0.860209  0.012221
surrey              0.121764  0.877780  0.000456
sussex              0.138597  0.861403  0.000000
thames-valley       0.095094  0.902950  0.001956
warwickshire        0.103109  0.895968  0.000923
west-mercia         0.116017  0.883477  0.000506
west-yorkshire      0.066904  0.933096  0.000000
wiltshire           0.123985  0.872325  0.003690

In [75]:
print(train['Age range'].value_counts(dropna=False,normalize=True))
pd.crosstab(train["station"],train["Age range"],normalize='index')

18-24       0.366184
25-34       0.239447
10-17       0.199456
over 34     0.194332
under 10    0.000581
Name: Age range, dtype: float64

Age range              10-17     18-24     25-34   over 34  under 10
station
avon-and-somerset   0.173540  0.312032  0.252621  0.261008  0.000799
bedfordshire        0.247802  0.400570  0.197672  0.152293  0.001663
btp                 0.241654  0.357614  0.214129  0.183987  0.002616
cambridgeshire      0.241733  0.340935  0.213227  0.200684  0.003421
cheshire            0.172136  0.317853  0.241692  0.268318  0.000000
city-of-london      0.072727  0.375105  0.337063  0.215105  0.000000
cleveland           0.119124  0.226496  0.288996  0.365385  0.000000
cumbria             0.167215  0.285580  0.267262  0.279004  0.000939
derbyshire          0.177770  0.342917  0.258766  0.220196  0.000351
devon-and-cornwall  0.186418  0.283129  0.246796  0.279958  0.003699
dorset              0.152566  0.272920  0.234690  0.339823  0.000000
durham              0.147588  0.296256  0.261699  0.293017  0.001440
dyfed-powys         0.191194  0.341831  0.234762  0.231518  0.000695
essex               0.245339  0.366406  0.217238  0.170755  0.000263
gloucestershire     0.224312  0.351445  0.220829  0.200627  0.002786
greater-manchester  0.224284  0.302000  0.238508  0.226757  0.008452
gwent               0.177461  0.367876  0.264249  0.190415  0.000000
hampshire           0.219724  0.343193  0.215498  0.221299  0.000286
hertfordshire       0.231993  0.388205  0.219988  0.159289  0.000525
humberside          0.201427  0.284430  0.244251  0.269099  0.000793
kent                0.204523  0.366895  0.236381  0.190097  0.002104
lancashire          0.219248  0.301726  0.242517  0.235525  0.000983
leicestershire      0.191767  0.390161  0.227510  0.190361  0.000201
lincolnshire        0.128393  0.330493  0.277393  0.263325  0.000396
merseyside          0.173714  0.345650  0.252542  0.227973  0.000120
metropolitan        0.201691  0.388626  0.236779  0.172713  0.000191
norfolk             0.193555  0.323289  0.239799  0.241682  0.001674
north-wales         0.161266  0.305465  0.232215  0.299137  0.001918
north-yorkshire     0.172784  0.237243  0.246643  0.342435  0.000895
northamptonshire    0.166761  0.373511  0.234827  0.224617  0.000284
northumbria         0.158604  0.277344  0.304157  0.259895  0.000000
nottinghamshire     0.150641  0.327608  0.281290  0.237083  0.003379
south-yorkshire     0.181694  0.302469  0.257653  0.257425  0.000760
staffordshire       0.212216  0.307461  0.242279  0.237360  0.000683
suffolk             0.231595  0.327571  0.230104  0.208346  0.002385
surrey              0.245808  0.419887  0.209169  0.124316  0.000820
sussex              0.228641  0.303991  0.242040  0.224751  0.000576
thames-valley       0.219801  0.369203  0.230193  0.178903  0.001900
warwickshire        0.189289  0.350262  0.251770  0.208064  0.000616
west-mercia         0.166118  0.344256  0.249367  0.240005  0.000253
west-yorkshire      0.185429  0.355518  0.264407  0.194412  0.000233
wiltshire           0.262731  0.343911  0.206642  0.186716  0.000000

In [76]:
print(train['Officer-defined ethnicity'].value_counts(dropna=False,normalize=True))
pd.crosstab(train["station"],train["Officer-defined ethnicity"],normalize='index')

White    0.572668
Black    0.264290
Asian    0.130235
Other    0.030036
Mixed    0.002770
Name: Officer-defined ethnicity, dtype: float64

Officer-defined ethnicity     Asian     Black     Mixed     Other     White
station
avon-and-somerset          0.028757  0.146580  0.042736  0.014279  0.767649
bedfordshire               0.231409  0.197672  0.000475  0.014018  0.556427
btp                        0.079226  0.306750  0.000000  0.018524  0.595500
cambridgeshire             0.076397  0.120867  0.000000  0.026226  0.776511
cheshire                   0.020846  0.031166  0.000000  0.003922  0.944066
city-of-london             0.210629  0.221538  0.000000  0.037762  0.530070
cleveland                  0.059295  0.026709  0.000000  0.012821  0.901175
cumbria                    0.016440  0.011273  0.000000  0.004227  0.968060
derbyshire                 0.110449  0.098527  0.000000  0.015428  0.775596
devon-and-cornwall         0.010437  0.029991  0.000000  0.006210  0.953362
dorset                     0.020531  0.120354  0.000000  0.007434  0.851681
durham                     0.012959  0.008999  0.000000  0.005400  0.972642
dyfed-powys                0.015064  0.019003  0.000232  0.010197  0.955504
essex                      0.042492  0.116760  0.000000  0.040969  0.799779
gloucestershire            0.022292  0.077325  0.000000  0.068617  0.831766
greater-manchester         0.138528  0.174397  0.000000  0.020202  0.666873
gwent                      0.081606  0.042746  0.000000  0.007772  0.867876
hampshire                  0.049273  0.130559  0.000000  0.023347  0.796820
hertfordshire              0.099040  0.192227  0.000000  0.025585  0.683148
humberside                 0.041766  0.045995  0.000000  0.000000  0.912239
kent                       0.038019  0.112706  0.023894  0.087309  0.738072
lancashire                 0.153485  0.029714  0.000000  0.003277  0.813524
leicestershire             0.174900  0.151004  0.000000  0.019277  0.654819
lincolnshire               0.017040  0.041411  0.000000  0.003963  0.937587
merseyside                 0.014352  0.045821  0.000000  0.010914  0.928913
metropolitan               0.174259  0.404342  0.000000  0.039434  0.381965
norfolk                    0.016740  0.071563  0.023645  0.008788  0.879263
north-wales                0.007478  0.011314  0.000000  0.066539  0.914669
north-yorkshire            0.030886  0.026410  0.000000  0.002686  0.940018
northamptonshire           0.055587  0.210437  0.000000  0.003403  0.730573
northumbria                0.050078  0.030785  0.008796  0.026812  0.883530
nottinghamshire            0.099958  0.154019  0.064480  0.015205  0.666338
south-yorkshire            0.091303  0.087125  0.000000  0.013369  0.808204
staffordshire              0.114376  0.083219  0.000000  0.009702  0.792703
suffolk                    0.025633  0.095976  0.053949  0.041133  0.783308
surrey                     0.100984  0.110645  0.003281  0.012213  0.772876
sussex                     0.048264  0.141478  0.000000  0.010517  0.799741
thames-valley              0.184713  0.193262  0.000000  0.003855  0.618170
warwickshire               0.084334  0.111111  0.030779  0.023700  0.750077
west-mercia                0.084008  0.063765  0.016574  0.017586  0.818067
west-yorkshire             0.268432  0.086619  0.000000  0.007583  0.637366
wiltshire                  0.059041  0.090775  0.000000  0.005904  0.844280

In [78]:
print(train['Removal of more than just outer clothing'].value_counts(dropna=False,normalize=True))
pd.crosstab(train["station"],train["Removal of more than just outer clothing"],normalize='index',dropna=False)

NaN      0.645689
False    0.338167
True     0.016144
Name: Removal of more than just outer clothing, dtype: float64

Removal of more than just outer clothing     False     True
station
avon-and-somerset                         0.936843  0.063157
bedfordshire                              0.977995  0.022005
btp                                       0.996964  0.003036
cambridgeshire                            0.974857  0.025143
cheshire                                  0.956693  0.043307
city-of-london                            0.965459  0.034541
cumbria                                   0.931262  0.068738
derbyshire                                0.920757  0.079243
devon-and-cornwall                        0.979981  0.020019
dorset                                    0.871858  0.128142
durham                                    0.978491  0.021509
dyfed-powys                               0.916570  0.083430
essex                                     0.967593  0.032407
gloucestershire                           0.964317  0.035683
greater-manchester                        0.979386  0.020614
hampshire                                 0.925200  0.074800
hertfordshire                             0.931448  0.068552
humberside                                0.972509  0.027491
kent                                      0.942363  0.057637
lancashire                                0.884836  0.115164
leicestershire                            0.971066  0.028934
lincolnshire                              0.963851  0.036149
merseyside                                0.967786  0.032214
norfolk                                   0.953128  0.046872
north-wales                               0.959732  0.040268
northamptonshire                          0.931083  0.068917
northumbria                               0.940275  0.059725
nottinghamshire                           0.971280  0.028720
south-yorkshire                           0.000000  1.000000
staffordshire                             0.929352  0.070648
suffolk                                   0.892399  0.107601
sussex                                    0.953753  0.046247
thames-valley                             0.976702  0.023298
warwickshire                              0.679487  0.320513
west-mercia                               0.683860  0.316140
west-yorkshire                            0.982618  0.017382
wiltshire                                 0.939024  0.060976

In [84]:
pd.crosstab(train["station"],train["Object of search"],values=train["target1"], aggfunc='mean')

Object of search,Anything to threaten or harm anyone,Article for use in theft,Articles for use in criminal damage,Controlled drugs,Crossbows,Detailed object of search unavailable,Evidence of offences under the Act,Evidence of wildlife offences,Firearms,Fireworks,Game or poaching equipment,Goods on which duty has not been paid etc.,Offensive weapons,Psychoactive substances,Seals or hunting equipment,Stolen goods
station,,,,,,,,,,,,,,,,
avon-and-somerset,0.058824,0.228512,0.233696,0.337909,0.000000,NaN,0.305556,NaN,0.183099,0.250000,0.000000,0.5,0.193736,0.800000,NaN,0.295209
bedfordshire,0.000000,0.173258,0.137931,0.297348,NaN,NaN,NaN,NaN,0.130435,0.333333,NaN,NaN,0.137589,0.000000,NaN,0.264069
btp,0.094340,0.279683,0.416667,0.316567,0.000000,NaN,0.141176,1.000000,0.191489,NaN,NaN,0.0,0.162730,0.454545,NaN,0.326049
cambridgeshire,NaN,0.234899,0.400000,0.422397,NaN,NaN,NaN,NaN,0.333333,NaN,NaN,NaN,0.347305,NaN,NaN,0.317073
cheshire,NaN,0.311778,0.418182,0.412511,0.000000,NaN,NaN,NaN,0.466667,0.200000,NaN,NaN,0.270380,NaN,NaN,0.473310
city-of-london,0.105263,0.302360,0.111111,0.395833,NaN,NaN,0.236559,NaN,0.171429,0.000000,NaN,NaN,0.161417,0.000000,NaN,0.308140
cleveland,0.384615,0.240506,0.259259,0.342324,NaN,NaN,0.588235,NaN,0.250000,NaN,NaN,NaN,0.317073,NaN,NaN,0.336538
cumbria,NaN,0.198864,0.184211,0.267547,NaN,NaN,NaN,NaN,0.333333,0.181818,0.000000,NaN,0.272727,NaN,NaN,0.394619
derbyshire,NaN,0.247500,0.391304,0.345257,NaN,NaN,0.238095,NaN,0.516129,0.000000,NaN,0.0,0.218421,NaN,NaN,0.317829
devon-and-cornwall,NaN,0.173077,0.212121,0.325518,NaN,NaN,NaN,NaN,0.314286,NaN,NaN,NaN,0.228571,NaN,NaN,0.303659
dorset,NaN,0.199219,0.142857,0.255507,NaN,NaN,0.000000,0.666667,0.200000,NaN,0.166667,NaN,0.187898,NaN,NaN,0.220000
durham,NaN,0.323789,0.447368,0.496924,NaN,NaN,NaN,NaN,0.482759,0.200000,0.473684,0.0,0.411215,0.000000,NaN,0.496629
dyfed-powys,0.248562,0.251497,0.106383,0.336902,0.666667,NaN,0.346154,NaN,0.391304,NaN,NaN,NaN,0.000000,NaN,NaN,0.500000
essex,0.078886,0.220641,0.152284,0.343829,NaN,NaN,0.177632,NaN,0.218182,NaN,NaN,NaN,0.206317,NaN,NaN,0.350951
gloucestershire,NaN,0.173077,0.121951,0.326520,NaN,NaN,NaN,0.000000,0.075000,NaN,0.000000,NaN,0.159468,NaN,NaN,0.260317
greater-manchester,0.208861,0.191549,0.222222,0.319780,NaN,NaN,NaN,NaN,0.208333,0.071429,NaN,NaN,0.178035,1.000000,NaN,0.266667
gwent,NaN,0.019608,0.000000,0.044408,NaN,NaN,NaN,NaN,0.071429,NaN,NaN,NaN,0.026316,NaN,NaN,0.000000
hampshire,0.294020,0.352642,0.307692,0.448559,1.000000,NaN,0.283019,0.000000,0.268293,0.333333,0.000000,1.0,0.338963,1.000000,NaN,0.479506
hertfordshire,0.000000,0.236772,0.080460,0.344041,NaN,NaN,NaN,NaN,0.150000,0.044444,0.555556,NaN,0.184257,0.000000,NaN,0.377049
humberside,0.081081,0.208835,0.272727,0.278431,NaN,NaN,NaN,0.000000,0.086957,0.000000,0.000000,NaN,0.213499,NaN,NaN,0.263014
kent,NaN,0.303415,0.317757,0.444978,NaN,NaN,0.279070,NaN,0.303867,NaN,NaN,NaN,0.314969,0.441447,NaN,0.460348
lancashire,NaN,0.136070,0.211728,0.288519,NaN,NaN,NaN,NaN,0.066667,0.149457,NaN,NaN,0.175000,NaN,NaN,0.269147
leicestershire,NaN,0.204955,0.114286,0.347712,NaN,NaN,0.291667,NaN,0.446429,NaN,NaN,NaN,0.280992,0.200000,NaN,0.324165
lincolnshire,0.750000,0.150084,0.088889,0.245753,NaN,NaN,0.146789,0.000000,0.127660,0.000000,NaN,0.0,0.137374,0.166667,0.0,0.240196
merseyside,NaN,0.116183,0.057034,0.251538,0.250000,NaN,0.060403,NaN,0.085308,0.031008,NaN,0.0,0.113338,NaN,NaN,0.162921
metropolitan,0.134977,NaN,0.295731,0.305135,NaN,NaN,0.228908,NaN,0.283103,0.094660,NaN,NaN,0.200798,NaN,NaN,0.305316
norfolk,0.128788,0.146154,0.137931,0.259372,0.000000,NaN,0.075758,0.250000,0.173913,0.000000,1.000000,0.0,0.187675,0.260870,NaN,0.251232
north-wales,NaN,0.106742,0.270270,0.205501,NaN,NaN,NaN,NaN,0.122449,NaN,0.000000,NaN,0.152727,NaN,NaN,0.213555
north-yorkshire,NaN,0.234127,0.133333,0.190761,NaN,NaN,NaN,NaN,0.200000,NaN,NaN,NaN,0.152027,NaN,NaN,0.255187
northamptonshire,NaN,0.159705,0.181818,0.326316,NaN,NaN,0.238095,NaN,0.137931,0.000000,0.000000,NaN,0.200461,NaN,NaN,0.294872
northumbria,0.000000,0.224771,0.221198,0.293272,1.000000,NaN,0.500000,0.500000,0.277778,0.400000,0.437500,NaN,0.287921,0.500000,NaN,0.338997
nottinghamshire,NaN,0.271300,0.357143,0.371913,NaN,NaN,NaN,NaN,0.142857,0.181818,0.000000,1.0,0.249707,0.500000,NaN,0.364261
south-yorkshire,0.262411,0.153846,0.156682,0.270547,NaN,NaN,NaN,NaN,0.196429,0.094595,NaN,NaN,0.219616,NaN,NaN,0.333530
staffordshire,0.285714,0.171141,0.267857,0.354999,NaN,NaN,NaN,NaN,0.174419,NaN,NaN,NaN,0.182665,NaN,NaN,0.391020
suffolk,0.268908,0.211712,0.111111,0.317439,NaN,NaN,0.318182,0.500000,0.285714,NaN,0.000000,NaN,0.219949,0.196721,1.0,0.356061
surrey,0.120401,0.240228,0.255102,0.322851,NaN,NaN,NaN,NaN,0.180085,0.000000,0.166667,NaN,0.221849,NaN,NaN,0.392473
sussex,0.247059,0.351375,0.349206,0.458839,NaN,0.261905,0.228070,NaN,0.303571,0.256410,0.000000,NaN,0.514134,NaN,NaN,0.377510
thames-valley,0.046547,0.179104,0.173913,0.277976,0.000000,NaN,0.181818,NaN,0.155738,0.000000,NaN,NaN,0.181646,NaN,NaN,0.292958
warwickshire,0.178571,0.205941,0.250000,0.351526,1.000000,0.263158,0.500000,NaN,0.203704,0.000000,0.000000,0.0,0.248139,0.444444,NaN,0.345538
west-mercia,0.229885,0.246299,0.181818,0.375027,NaN,0.307692,0.375000,NaN,0.241379,0.000000,0.500000,NaN,0.266010,0.333333,NaN,0.401951
west-yorkshire,NaN,0.232842,0.172414,0.415080,NaN,NaN,0.000000,NaN,0.300000,0.202381,NaN,NaN,0.319245,0.066667,NaN,0.405422
wiltshire,0.000000,0.092308,0.363636,0.261672,NaN,NaN,0.166667,NaN,0.285714,NaN,NaN,NaN,0.149733,NaN,NaN,0.195652

In [85]:
pd.crosstab(train["station"],train["Object of search"],values=train["target2"], aggfunc='mean')

Object of search,Anything to threaten or harm anyone,Article for use in theft,Articles for use in criminal damage,Controlled drugs,Crossbows,Detailed object of search unavailable,Evidence of offences under the Act,Evidence of wildlife offences,Firearms,Fireworks,Game or poaching equipment,Goods on which duty has not been paid etc.,Offensive weapons,Psychoactive substances,Seals or hunting equipment,Stolen goods
station,,,,,,,,,,,,,,,,
avon-and-somerset,0.058824,0.192872,0.195652,0.193242,0.000000,NaN,0.240741,NaN,0.140845,0.250000,0.000000,0.50,0.168973,0.200000,NaN,0.216383
bedfordshire,0.000000,0.118644,0.103448,0.122152,NaN,NaN,NaN,NaN,0.086957,0.000000,NaN,NaN,0.102128,0.000000,NaN,0.168831
btp,0.082333,0.266491,0.312500,0.181750,0.000000,NaN,0.117647,1.00,0.191489,NaN,NaN,0.00,0.138058,0.363636,NaN,0.278846
cambridgeshire,NaN,0.174497,0.000000,0.284872,NaN,NaN,NaN,NaN,0.333333,NaN,NaN,NaN,0.281437,NaN,NaN,0.292683
cheshire,NaN,0.200924,0.090909,0.225446,0.000000,NaN,NaN,NaN,0.200000,0.000000,NaN,NaN,0.171196,NaN,NaN,0.320285
city-of-london,0.078947,0.280236,0.111111,0.263021,NaN,NaN,0.215054,NaN,0.171429,0.000000,NaN,NaN,0.145669,0.000000,NaN,0.267442
cleveland,0.384615,0.231013,0.240741,0.263485,NaN,NaN,0.588235,NaN,0.178571,NaN,NaN,NaN,0.288618,NaN,NaN,0.326923
cumbria,NaN,0.176136,0.131579,0.173732,NaN,NaN,NaN,NaN,0.333333,0.000000,0.000000,NaN,0.251082,NaN,NaN,0.331839
derbyshire,NaN,0.205000,0.217391,0.188076,NaN,NaN,0.214286,NaN,0.483871,0.000000,NaN,0.00,0.197368,NaN,NaN,0.224806
devon-and-cornwall,NaN,0.153846,0.181818,0.142651,NaN,NaN,NaN,NaN,0.257143,NaN,NaN,NaN,0.202041,NaN,NaN,0.247561
dorset,NaN,0.128906,0.107143,0.150269,NaN,NaN,0.000000,0.00,0.200000,NaN,0.000000,NaN,0.159236,NaN,NaN,0.186667
durham,NaN,0.211454,0.105263,0.272727,NaN,NaN,NaN,NaN,0.275862,0.000000,0.052632,0.00,0.280374,0.000000,NaN,0.305618
dyfed-powys,0.220944,0.233533,0.085106,0.196788,0.333333,NaN,0.307692,NaN,0.347826,NaN,NaN,NaN,0.000000,NaN,NaN,0.500000
essex,0.030162,0.167260,0.050761,0.126342,NaN,NaN,0.092105,NaN,0.209091,NaN,NaN,NaN,0.158337,NaN,NaN,0.216350
gloucestershire,NaN,0.153846,0.121951,0.183955,NaN,NaN,NaN,0.00,0.050000,NaN,0.000000,NaN,0.152824,NaN,NaN,0.209524
greater-manchester,0.177215,0.156338,0.158730,0.157560,NaN,NaN,NaN,NaN,0.166667,0.071429,NaN,NaN,0.152601,0.500000,NaN,0.187302
gwent,NaN,0.019608,0.000000,0.013158,NaN,NaN,NaN,NaN,0.071429,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000
hampshire,0.240864,0.275407,0.153846,0.236475,1.000000,NaN,0.188679,0.00,0.207317,0.000000,0.000000,0.75,0.282268,1.000000,NaN,0.358748
hertfordshire,0.000000,0.205026,0.034483,0.182190,NaN,NaN,NaN,NaN,0.125000,0.022222,0.555556,NaN,0.149271,0.000000,NaN,0.341530
humberside,0.081081,0.180723,0.204545,0.152451,NaN,NaN,NaN,0.00,0.086957,0.000000,0.000000,NaN,0.194215,NaN,NaN,0.205479
kent,NaN,0.189268,0.149533,0.208151,NaN,NaN,0.205426,NaN,0.215470,NaN,NaN,NaN,0.221480,0.180263,NaN,0.300451
lancashire,NaN,0.123754,0.132788,0.175491,NaN,NaN,NaN,NaN,0.050000,0.133152,NaN,NaN,0.163333,NaN,NaN,0.214442
leicestershire,NaN,0.173423,0.085714,0.164052,NaN,NaN,0.291667,NaN,0.392857,NaN,NaN,NaN,0.246753,0.000000,NaN,0.267191
lincolnshire,0.500000,0.143339,0.088889,0.145527,NaN,NaN,0.110092,0.00,0.106383,0.000000,NaN,0.00,0.133333,0.166667,0.0,0.225490
merseyside,NaN,0.092563,0.045627,0.138163,0.000000,NaN,0.046980,NaN,0.075829,0.015504,NaN,0.00,0.094552,NaN,NaN,0.143820
metropolitan,0.066970,NaN,0.249502,0.142107,NaN,NaN,0.193593,NaN,0.250609,0.055016,NaN,NaN,0.168926,NaN,NaN,0.239149
norfolk,0.113636,0.110256,0.080460,0.143554,0.000000,NaN,0.060606,0.25,0.043478,0.000000,1.000000,0.00,0.151261,0.130435,NaN,0.157635
north-wales,NaN,0.101124,0.189189,0.129624,NaN,NaN,NaN,NaN,0.122449,NaN,0.000000,NaN,0.141818,NaN,NaN,0.170077
north-yorkshire,NaN,0.178571,0.133333,0.156544,NaN,NaN,NaN,NaN,0.150000,NaN,NaN,NaN,0.148649,NaN,NaN,0.195021
northamptonshire,NaN,0.132678,0.181818,0.186947,NaN,NaN,0.171429,NaN,0.068966,0.000000,0.000000,NaN,0.186636,NaN,NaN,0.250000
northumbria,0.000000,0.192661,0.195853,0.223820,1.000000,NaN,0.500000,0.50,0.250000,0.400000,0.437500,NaN,0.279494,0.500000,NaN,0.305013
nottinghamshire,NaN,0.190583,0.285714,0.244379,NaN,NaN,NaN,NaN,0.119048,0.090909,0.000000,1.00,0.213365,0.500000,NaN,0.305842
south-yorkshire,0.219858,0.130960,0.110599,0.159256,NaN,NaN,NaN,NaN,0.166667,0.013514,NaN,NaN,0.201493,NaN,NaN,0.210744
staffordshire,0.285714,0.115772,0.196429,0.178064,NaN,NaN,NaN,NaN,0.151163,NaN,NaN,NaN,0.139795,NaN,NaN,0.259121
suffolk,0.218487,0.171171,0.111111,0.188465,NaN,NaN,0.204545,0.50,0.214286,NaN,0.000000,NaN,0.179028,0.098361,1.0,0.223485
surrey,0.068004,0.192182,0.193878,0.144740,NaN,NaN,NaN,NaN,0.150424,0.000000,0.000000,NaN,0.183193,NaN,NaN,0.276882
sussex,0.219608,0.197595,0.111111,0.163588,NaN,0.226190,0.192982,NaN,0.160714,0.000000,0.000000,NaN,0.167845,NaN,NaN,0.231593
thames-valley,0.033033,0.160625,0.130435,0.170997,0.000000,NaN,0.090909,NaN,0.139344,0.000000,NaN,NaN,0.161779,NaN,NaN,0.266479
warwickshire,0.178571,0.168317,0.208333,0.207746,1.000000,0.263158,0.500000,NaN,0.203704,0.000000,0.000000,0.00,0.223325,0.222222,NaN,0.283753
west-mercia,0.195402,0.215343,0.121212,0.237096,NaN,0.269231,0.343750,NaN,0.172414,0.000000,0.428571,NaN,0.250246,0.238095,NaN,0.313171
west-yorkshire,NaN,0.204325,0.124138,0.224514,NaN,NaN,0.000000,NaN,0.290323,0.059524,NaN,NaN,0.301709,0.066667,NaN,0.348121
wiltshire,0.000000,0.061538,0.363636,0.124864,NaN,NaN,0.125000,NaN,0.285714,NaN,NaN,NaN,0.139037,NaN,NaN,0.166667

In [87]:
pd.crosstab(train["station"],train["Gender"],values=train["target1"], aggfunc='mean')

Gender                Female      Male     Other
station
avon-and-somerset   0.238024  0.310520       NaN
bedfordshire        0.208443  0.255425  0.000000
btp                 0.273115  0.270200  0.333333
cambridgeshire      0.335766  0.377537  0.000000
cheshire            0.351981  0.388134       NaN
city-of-london      0.274011  0.342138  0.666667
cleveland           0.274286  0.325280       NaN
cumbria             0.231023  0.281096  0.000000
derbyshire          0.215054  0.324650  0.000000
devon-and-cornwall  0.263158  0.314974       NaN
dorset              0.185615  0.248956       NaN
durham              0.350943  0.467678  0.428571
dyfed-powys         0.250000  0.325061       NaN
essex               0.268622  0.310580       NaN
gloucestershire     0.226708  0.290310       NaN
greater-manchester  0.235450  0.264699       NaN
gwent               0.017241  0.040616       NaN
hampshire           0.442364  0.429554  0.347826
hertfordshire       0.261111  0.309976       NaN
humberside          0.195804  0.255814       NaN
kent                0.384762  0.415374       NaN
lancashire          0.176319  0.206509  0.105263
leicestershire      0.225951  0.329583       NaN
lincolnshire        0.181197  0.223817  0.333333
merseyside          0.215836  0.224470  0.500000
metropolitan        0.265867  0.274195  0.257143
norfolk             0.208274  0.239622  0.236364
north-wales         0.172241  0.193632       NaN
north-yorkshire     0.200528  0.204852       NaN
northamptonshire    0.226537  0.290333       NaN
northumbria         0.311978  0.291930  0.272727
nottinghamshire     0.291837  0.353155  0.500000
south-yorkshire     0.262724  0.252412       NaN
staffordshire       0.313316  0.317890  0.166667
suffolk             0.242991  0.305960  0.219512
surrey              0.220808  0.295712  0.000000
sussex              0.384615  0.424318       NaN
thames-valley       0.227967  0.253017  0.257143
warwickshire        0.301493  0.308485  0.000000
west-mercia         0.343511  0.345553  0.500000
west-yorkshire      0.317350  0.364131       NaN
wiltshire           0.202381  0.235195  0.000000

In [88]:
pd.crosstab(train["station"],train["Gender"],values=train["target2"], aggfunc='mean')

Gender                Female      Male     Other
station
avon-and-somerset   0.159431  0.196106       NaN
bedfordshire        0.105541  0.121830  0.000000
btp                 0.200569  0.180811  0.333333
cambridgeshire      0.189781  0.278755  0.000000
cheshire            0.167832  0.223053       NaN
city-of-london      0.183616  0.259789  0.333333
cleveland           0.222857  0.276959       NaN
cumbria             0.158416  0.204384  0.000000
derbyshire          0.121864  0.205288  0.000000
devon-and-cornwall  0.136672  0.167423       NaN
dorset              0.102088  0.159148       NaN
durham              0.181132  0.273743  0.000000
dyfed-powys         0.140432  0.214617       NaN
essex               0.106611  0.141140       NaN
gloucestershire     0.152174  0.181248       NaN
greater-manchester  0.132275  0.163425       NaN
gwent               0.000000  0.014006       NaN
hampshire           0.258046  0.262205  0.086957
hertfordshire       0.153472  0.198351       NaN
humberside          0.125874  0.172630       NaN
kent                0.186032  0.219618       NaN
lancashire          0.124839  0.146566  0.052632
leicestershire      0.116331  0.199426       NaN
lincolnshire        0.116239  0.149585  0.333333
merseyside          0.109727  0.130431  0.250000
metropolitan        0.141705  0.161014  0.171429
norfolk             0.112696  0.144171  0.090909
north-wales         0.120401  0.137968       NaN
north-yorkshire     0.126649  0.174124       NaN
northamptonshire    0.135922  0.185887       NaN
northumbria         0.245125  0.247785  0.181818
nottinghamshire     0.171429  0.244364  0.000000
south-yorkshire     0.138927  0.171207       NaN
staffordshire       0.177546  0.179358  0.166667
suffolk             0.147196  0.196119  0.097561
surrey              0.108533  0.156578  0.000000
sussex              0.165281  0.180130       NaN
thames-valley       0.155112  0.174865  0.228571
warwickshire        0.188060  0.217108  0.000000
west-mercia         0.213740  0.248461  0.500000
west-yorkshire      0.183086  0.245046       NaN
wiltshire           0.077381  0.138748  0.000000

In [89]:
pd.crosstab(train["station"],train["Gender"],values=train["target2"], aggfunc='mean')

Gender                Female      Male     Other
station
avon-and-somerset   0.159431  0.196106       NaN
bedfordshire        0.105541  0.121830  0.000000
btp                 0.200569  0.180811  0.333333
cambridgeshire      0.189781  0.278755  0.000000
cheshire            0.167832  0.223053       NaN
city-of-london      0.183616  0.259789  0.333333
cleveland           0.222857  0.276959       NaN
cumbria             0.158416  0.204384  0.000000
derbyshire          0.121864  0.205288  0.000000
devon-and-cornwall  0.136672  0.167423       NaN
dorset              0.102088  0.159148       NaN
durham              0.181132  0.273743  0.000000
dyfed-powys         0.140432  0.214617       NaN
essex               0.106611  0.141140       NaN
gloucestershire     0.152174  0.181248       NaN
greater-manchester  0.132275  0.163425       NaN
gwent               0.000000  0.014006       NaN
hampshire           0.258046  0.262205  0.086957
hertfordshire       0.153472  0.198351       NaN
humberside          0.125874  0.172630       NaN
kent                0.186032  0.219618       NaN
lancashire          0.124839  0.146566  0.052632
leicestershire      0.116331  0.199426       NaN
lincolnshire        0.116239  0.149585  0.333333
merseyside          0.109727  0.130431  0.250000
metropolitan        0.141705  0.161014  0.171429
norfolk             0.112696  0.144171  0.090909
north-wales         0.120401  0.137968       NaN
north-yorkshire     0.126649  0.174124       NaN
northamptonshire    0.135922  0.185887       NaN
northumbria         0.245125  0.247785  0.181818
nottinghamshire     0.171429  0.244364  0.000000
south-yorkshire     0.138927  0.171207       NaN
staffordshire       0.177546  0.179358  0.166667
suffolk             0.147196  0.196119  0.097561
surrey              0.108533  0.156578  0.000000
sussex              0.165281  0.180130       NaN
thames-valley       0.155112  0.174865  0.228571
warwickshire        0.188060  0.217108  0.000000
west-mercia         0.213740  0.248461  0.500000
west-yorkshire      0.183086  0.245046       NaN
wiltshire           0.077381  0.138748  0.000000

In [93]:
pd.crosstab(train["station"],train["Type"],values=train["target1"], aggfunc='mean')

Type                Person and Vehicle search  Person search  Vehicle search
station
avon-and-somerset                    0.326401       0.292989             NaN
bedfordshire                         0.393606       0.206195        0.250000
btp                                  0.475000       0.269571        0.272727
cambridgeshire                       0.537634       0.325615             NaN
cheshire                             0.460251       0.366418             NaN
city-of-london                       0.446463       0.289838             NaN
cleveland                            0.388350       0.316355        0.500000
cumbria                              0.379679       0.249143        1.000000
derbyshire                           0.415686       0.291631             NaN
devon-and-cornwall                   0.469707       0.267705             NaN
dorset                                    NaN       0.239292             NaN
durham                               0.501636       0.434175             NaN
dyfed-powys                          0.468208       0.264876             NaN
essex                                0.391243       0.269682             NaN
gloucestershire                      0.426564       0.229406             NaN
greater-manchester                   0.423986       0.239161        0.466667
gwent                                     NaN       0.038860             NaN
hampshire                                 NaN       0.430853             NaN
hertfordshire                        0.416109       0.256322             NaN
humberside                           0.361162       0.229889             NaN
kent                                 0.340553       0.480018        0.470588
lancashire                           0.272064       0.170195             NaN
leicestershire                       0.448882       0.301791             NaN
lincolnshire                         0.237251       0.214958             NaN
merseyside                           0.239778       0.220181             NaN
metropolitan                         0.353079       0.248748        0.342482
norfolk                                   NaN       0.234986             NaN
north-wales                          0.297111       0.174020             NaN
north-yorkshire                      0.235075       0.194346             NaN
northamptonshire                          NaN       0.284742             NaN
northumbria                          0.385802       0.289517             NaN
nottinghamshire                      0.463190       0.330776             NaN
south-yorkshire                           NaN       0.253551             NaN
staffordshire                        0.408353       0.289060             NaN
suffolk                                   NaN       0.296870             NaN
surrey                               0.000000       0.288613             NaN
sussex                               0.491629       0.393474             NaN
thames-valley                        0.258545       0.150497             NaN
warwickshire                         0.361480       0.281549             NaN
west-mercia                          0.446306       0.295188             NaN
west-yorkshire                       0.471217       0.308606             NaN
wiltshire                            0.363388       0.180162        1.000000

In [94]:
print(train['Type'].value_counts(dropna=False,normalize=True))
pd.crosstab(train["Type"],train["target1"],normalize='index',dropna=False)

Person search                0.762178
Person and Vehicle search    0.236381
Vehicle search               0.001441
Name: Type, dtype: float64

target1                       False     True
Type
Person and Vehicle search  0.649197  0.350803
Person search              0.736601  0.263399
Vehicle search             0.643908  0.356092

In [95]:
pd.crosstab(train["Type"],train["target2"],normalize='index',dropna=False)

target2                       False     True
Type
Person and Vehicle search  0.790568  0.209432
Person search              0.842629  0.157371
Vehicle search             0.771008  0.228992

In [97]:
print(train['Part of a policing operation'].value_counts(dropna=False,normalize=True))
pd.crosstab(train["Part of a policing operation"],train["target1"],normalize='index',dropna=False)

False    0.742908
NaN      0.232458
True     0.024635
Name: Part of a policing operation, dtype: float64

target1                          False     True
Part of a policing operation
False                         0.715449  0.284551
True                          0.703330  0.296670

In [98]:
pd.crosstab(train["Part of a policing operation"],train["target2"],normalize='index',dropna=False)

target2                          False     True
Part of a policing operation
False                         0.832994  0.167006
True                          0.839990  0.160010

In [99]:
print(train['Officer-defined ethnicity'].value_counts(dropna=False,normalize=True))
pd.crosstab(train["Officer-defined ethnicity"],train["target1"],normalize='index',dropna=False)

White    0.572668
Black    0.264290
Asian    0.130235
Other    0.030036
Mixed    0.002770
Name: Officer-defined ethnicity, dtype: float64

target1                       False     True
Officer-defined ethnicity
Asian                      0.720800  0.279200
Black                      0.723506  0.276494
Mixed                      0.692896  0.307104
Other                      0.719182  0.280818
White                      0.711053  0.288947

In [100]:
pd.crosstab(train["Officer-defined ethnicity"],train["target2"],normalize='index',dropna=False)

target2                       False     True
Officer-defined ethnicity
Asian                      0.850584  0.149416
Black                      0.821883  0.178117
Mixed                      0.796175  0.203825
Other                      0.836105  0.163895
White                      0.829291  0.170709